var webpack=require('webpack');
var path=require('path');

module.exports={
	entry:path.join(__dirname,'/src/app/entry.js'),
	output:{
		path:path.join(__dirname,'/dist/js'),
		filename:'bundle.js',
		publicPath:'/js/'
	},
	watch:true,
	devtool:'source-map',
	module:{
		loaders:[
			{
				test:/\.css$/,
				loader:'style!css'
			},
			{
				test:/\.scss$/,
				loaders:['style','css','postcss','sass']
			},
			{
				test:/\.vue$/,
				loader:'vue',
				options:{
					loaders:{
						scss:'style!css!postcss!sass'
					}
				}
			},
			{
				test:/\.js?$/,
				exclude:/(node_modules)/,
				loader:'babel',
			},
			{
				test:/\.(png|jpg|jpeg|svg|gif)$/,
				loader:'file',
				query:{
					name:'app/images/[name]_[hash].[ext]'
				}
			},
		]
	},
	externals:{
		'jquery':'jQuery',
		'vue':'Vue',
		'lodash':'_'
	},
	resolve:{
		extensions:['','.vue','.js','.jsx','.scss']
	},
}