/**
 * Created by chenbin on 2016/11/22.
 */
module.exports={
    sendData11(){
        return{
            iRet:1,
            info:'成功',
            data:[
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/loPCysBMGXaGb1SE2LVwJFM9Nu1h.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "10",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiabuswDPWATZCI0OhWLWyia6icZOxEU5oO9tTzut4w2prDDbb6KTS7mkLDribs9SQv5KmKI5wmUicNxq4/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM7NQkZfy1ibibeV5Z2Sicd6Pp9pGzXvADicuKibib8KNFGwqHPF5J7LZQyaLjrucqNnoXN6Q5LB9QjVZibgg/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLChRibCeOlw7QWy6hlHUialu3iaNZcGqFDcRWzZogoVNSxXAnicaiaibpcicfHWmia2cwDu0xyQOqSNkxd61Q/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujRZXic7ddCicgRDjKUVYZ7M96wxV0KrWJU8ia1j5UXHOjrrMj6qF2NvTJDYKHvXYdjicY5Ywl5IuKZafA/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaWNJtIKo1ZriaM9gWDibK0W4a6ykFyOAV9uTox1kz6ibgfyDH2Qcx6NTnWySWPK7y5b5tWTSCDsxXPT/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaVgC6Vh6jQz2C7LZT3BzzpEwgMe3HZ8YtFU3Gx9p1JYUbXM3R1uu1ibd2qIo1ATIcEK7ZlLbgictNd/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQysDcvJnylNAfoNCAhKOKnXfgVz7vbdo2XWgNe9qS969ezozI6HVuKnrDLicWw8NYYoFl6ofzylucz/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEKTMDWlqiayDPV5icBwAPicj5kc3AZgV4d2WDibQubfZYEo4Lr0uJmialnXD44dHVxhaEoEmZ4rvDakOmA/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujROkUibKPjiaSIYJMXHmibyz6iaFob0SibibUxIkicW3s7ibyiaWI9dD8LwCUMH0Xib75licepqHHr05PfqBmpn8aTGFywZocV/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM6YyQP8K44jjNgSRicw5NTGhp9SfWOkYpyMORCMlic71RibgiaTmMKPcggTbDbHfaoibgqIXib4OYsiaj28w/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLDRjfPe0BuxKeHfO54KkINyLYHXEZopsrP5fgIYq5UnZxzJMia7LYFbpNYpf6mCQgibjVxvdBmTnCTA/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHZbNUhCd3Y7eTdQvgFMqr3nH788W5GtgGhLys8rhWvNl8h3V6Ykf5aurMckTdwDNz6uvVgQ0rtd1nPT6bNcQX3/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaBicxJHPsicbIA8aOjbM4b9zSItTJv4iaYqFYqfxCj0GUgv8TTpIqWsn682TLSmYziczvGPZoeUHtAsru4ibyg4ZU0gEk/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEJZSwJ0I5konUtfGrr7g2BVrKemYDZLiciaQia7S1ibrjf2cmSCdfoicpVr2GuR3HNJQp4v8LqtjGfUwicg/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHMRSkkF04QLyuXefAVicDqP2gJBdpBncRYxn1bzlaYJzRfRYqzAna0TrSqoOiaZux2QD3jD0jQ5gbkTXxUO4qXUS/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHZbNUhCd3Y7T6eiagSUzR65qYj4bux1FuUZXrl5zIiammiaM5LxV2dMnVlEA7GAMYxGMCgeIombLyK7CkThOtjJ3H/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQyk3Ih6P4qmKrgpQSMp4DibsbByARNlaTI4zpR7RFudvFWpicCfhQQJYOcvUky1mousxTDDZiblkGXQib/0",
                    ]
                },
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/loPCysBMGXaGb1SE2LVwJFM9Nu1h.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "11",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiabuswDPWATZCI0OhWLWyia6icZOxEU5oO9tTzut4w2prDDbb6KTS7mkLDribs9SQv5KmKI5wmUicNxq4/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM7NQkZfy1ibibeV5Z2Sicd6Pp9pGzXvADicuKibib8KNFGwqHPF5J7LZQyaLjrucqNnoXN6Q5LB9QjVZibgg/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLChRibCeOlw7QWy6hlHUialu3iaNZcGqFDcRWzZogoVNSxXAnicaiaibpcicfHWmia2cwDu0xyQOqSNkxd61Q/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujRZXic7ddCicgRDjKUVYZ7M96wxV0KrWJU8ia1j5UXHOjrrMj6qF2NvTJDYKHvXYdjicY5Ywl5IuKZafA/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaWNJtIKo1ZriaM9gWDibK0W4a6ykFyOAV9uTox1kz6ibgfyDH2Qcx6NTnWySWPK7y5b5tWTSCDsxXPT/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaVgC6Vh6jQz2C7LZT3BzzpEwgMe3HZ8YtFU3Gx9p1JYUbXM3R1uu1ibd2qIo1ATIcEK7ZlLbgictNd/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQysDcvJnylNAfoNCAhKOKnXfgVz7vbdo2XWgNe9qS969ezozI6HVuKnrDLicWw8NYYoFl6ofzylucz/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEKTMDWlqiayDPV5icBwAPicj5kc3AZgV4d2WDibQubfZYEo4Lr0uJmialnXD44dHVxhaEoEmZ4rvDakOmA/0",

                    ]
                },
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/loPCysBMGXaGb1SE2LVwJFM9Nu1h.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "12",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",

                    ]
                }
            ]
        }
    },
    sendData12(){
        return{
            iRet:1,
            info:'成功',
            data:[
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/FqxxCWyNt2WAUkPp3cryD23uT3OG.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "110",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiabuswDPWATZCI0OhWLWyia6icZOxEU5oO9tTzut4w2prDDbb6KTS7mkLDribs9SQv5KmKI5wmUicNxq4/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM7NQkZfy1ibibeV5Z2Sicd6Pp9pGzXvADicuKibib8KNFGwqHPF5J7LZQyaLjrucqNnoXN6Q5LB9QjVZibgg/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLChRibCeOlw7QWy6hlHUialu3iaNZcGqFDcRWzZogoVNSxXAnicaiaibpcicfHWmia2cwDu0xyQOqSNkxd61Q/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujRZXic7ddCicgRDjKUVYZ7M96wxV0KrWJU8ia1j5UXHOjrrMj6qF2NvTJDYKHvXYdjicY5Ywl5IuKZafA/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaWNJtIKo1ZriaM9gWDibK0W4a6ykFyOAV9uTox1kz6ibgfyDH2Qcx6NTnWySWPK7y5b5tWTSCDsxXPT/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaVgC6Vh6jQz2C7LZT3BzzpEwgMe3HZ8YtFU3Gx9p1JYUbXM3R1uu1ibd2qIo1ATIcEK7ZlLbgictNd/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQysDcvJnylNAfoNCAhKOKnXfgVz7vbdo2XWgNe9qS969ezozI6HVuKnrDLicWw8NYYoFl6ofzylucz/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEKTMDWlqiayDPV5icBwAPicj5kc3AZgV4d2WDibQubfZYEo4Lr0uJmialnXD44dHVxhaEoEmZ4rvDakOmA/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujROkUibKPjiaSIYJMXHmibyz6iaFob0SibibUxIkicW3s7ibyiaWI9dD8LwCUMH0Xib75licepqHHr05PfqBmpn8aTGFywZocV/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM6YyQP8K44jjNgSRicw5NTGhp9SfWOkYpyMORCMlic71RibgiaTmMKPcggTbDbHfaoibgqIXib4OYsiaj28w/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLDRjfPe0BuxKeHfO54KkINyLYHXEZopsrP5fgIYq5UnZxzJMia7LYFbpNYpf6mCQgibjVxvdBmTnCTA/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHZbNUhCd3Y7eTdQvgFMqr3nH788W5GtgGhLys8rhWvNl8h3V6Ykf5aurMckTdwDNz6uvVgQ0rtd1nPT6bNcQX3/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaBicxJHPsicbIA8aOjbM4b9zSItTJv4iaYqFYqfxCj0GUgv8TTpIqWsn682TLSmYziczvGPZoeUHtAsru4ibyg4ZU0gEk/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEJZSwJ0I5konUtfGrr7g2BVrKemYDZLiciaQia7S1ibrjf2cmSCdfoicpVr2GuR3HNJQp4v8LqtjGfUwicg/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHMRSkkF04QLyuXefAVicDqP2gJBdpBncRYxn1bzlaYJzRfRYqzAna0TrSqoOiaZux2QD3jD0jQ5gbkTXxUO4qXUS/0",
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYHZbNUhCd3Y7T6eiagSUzR65qYj4bux1FuUZXrl5zIiammiaM5LxV2dMnVlEA7GAMYxGMCgeIombLyK7CkThOtjJ3H/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQyk3Ih6P4qmKrgpQSMp4DibsbByARNlaTI4zpR7RFudvFWpicCfhQQJYOcvUky1mousxTDDZiblkGXQib/0",
                    ]
                },
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/FqxxCWyNt2WAUkPp3cryD23uT3OG.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "111",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiabuswDPWATZCI0OhWLWyia6icZOxEU5oO9tTzut4w2prDDbb6KTS7mkLDribs9SQv5KmKI5wmUicNxq4/0",
                        "http://wx.qlogo.cn/mmopen/Q3auHgzwzM7NQkZfy1ibibeV5Z2Sicd6Pp9pGzXvADicuKibib8KNFGwqHPF5J7LZQyaLjrucqNnoXN6Q5LB9QjVZibgg/0",
                        "http://wx.qlogo.cn/mmopen/ajNVdqHZLLChRibCeOlw7QWy6hlHUialu3iaNZcGqFDcRWzZogoVNSxXAnicaiaibpcicfHWmia2cwDu0xyQOqSNkxd61Q/0",
                        "http://wx.qlogo.cn/mmopen/QAm7hEbaujRZXic7ddCicgRDjKUVYZ7M96wxV0KrWJU8ia1j5UXHOjrrMj6qF2NvTJDYKHvXYdjicY5Ywl5IuKZafA/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaWNJtIKo1ZriaM9gWDibK0W4a6ykFyOAV9uTox1kz6ibgfyDH2Qcx6NTnWySWPK7y5b5tWTSCDsxXPT/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6icic7qlkupUPPiaVgC6Vh6jQz2C7LZT3BzzpEwgMe3HZ8YtFU3Gx9p1JYUbXM3R1uu1ibd2qIo1ATIcEK7ZlLbgictNd/0",
                        "http://wx.qlogo.cn/mmopen/ibuiacbAZyaB9AcmTufdlQysDcvJnylNAfoNCAhKOKnXfgVz7vbdo2XWgNe9qS969ezozI6HVuKnrDLicWw8NYYoFl6ofzylucz/0",
                        "http://wx.qlogo.cn/mmopen/PiajxSqBRaEKTMDWlqiayDPV5icBwAPicj5kc3AZgV4d2WDibQubfZYEo4Lr0uJmialnXD44dHVxhaEoEmZ4rvDakOmA/0",

                    ]
                },
                {
                    cate:"培训营",
                    cate_id: "2",
                    city: "上海",
                    cover_url: "http://7xopel.com2.z0.glb.qiniucdn.com/ke/cover/FqxxCWyNt2WAUkPp3cryD23uT3OG.jpg",
                    day: "2",
                    end_date: "1480521600",
                    guest: {id: "172", name: "简宁", position: "青岛艾俪婚礼创始人"},
                    guest_id: "172",
                    id: "112",
                    last_num: 6,
                    num: "34",
                    original_price: "1280",
                    price: "1280",
                    start_date: "11月30-12月01日",
                    title: "简宁丨宴会设计灵感提炼及创意应用",
                    total: "40",
                    user:[
                        "http://wx.qlogo.cn/mmopen/ccsP70UGcYF7865TPPamMJwS5KtG4iaHPUcjtt8lGcrpAqRZ4h3JdlSichhnkajny6JhiawBdMgeCz1l4hrzFUY7YBZElkgMRMK/0",
                        "http://wx.qlogo.cn/mmopen/YZjIPyEJ6ic9455BWfS8cvCYJXibKm5jBia5AgKyKFzxG6ric5BaxjuZ1azXB3xdDwtIuxibOb6vzkRm3QpeZGLD9Eg7MKLyEdiaNo/0",

                    ]
                }
            ]
        }
    }
}